# Generated by Django 6.0.2 on 2026-02-21 09:26

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text="Texte d'introduction affiché en haut de la page.", verbose_name='Introduction')),
                ('events_per_page', models.PositiveIntegerField(default=10, help_text="Nombre d'événements affichés par page.", verbose_name='Événements par page')),
            ],
            options={
                'verbose_name': 'Index des événements',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date_event', models.DateTimeField(verbose_name="Date de l'événement")),
                ('notes', wagtail.fields.StreamField([('richtext', 0), ('url', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Texte'}), 1: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL externe', 'label': 'Lien'})}, verbose_name='Notes et Comptes-rendus')),
            ],
            options={
                'verbose_name': 'Événement',
                'ordering': ['-date_event'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Légende')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_images', to='events.eventpage')),
            ],
            options={
                'verbose_name': "Image de l'événement",
            },
        ),
        migrations.CreateModel(
            name='EventDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True, help_text='Remarques spécifiques à cet événement')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customdocument', verbose_name='Document')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_documents', to='events.eventpage')),
            ],
            options={
                'verbose_name': "Document de l'événement",
                'ordering': ['document__document_date'],
            },
        ),
    ]
