# Generated by Django 6.0.2 on 2026-02-14 17:42

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date_event', models.DateTimeField(verbose_name="Date de l'événement")),
                ('notes', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('todo_list', 3), ('document', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'label': 'Titre de section'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Texte/Note'}), 2: ('wagtail.blocks.CharBlock', (), {}), 3: ('wagtail.blocks.ListBlock', (2,), {'label': 'Liste de tâches'}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Document annexe'})}, verbose_name='Notes et Comptes-rendus')),
            ],
            options={
                'verbose_name': 'Événement',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EventDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True, help_text='Remarques spécifiques à cet événement')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customdocument', verbose_name='Document')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_documents', to='events.eventpage')),
            ],
            options={
                'verbose_name': "Document de l'événement",
                'ordering': ['document__document_date'],
            },
        ),
    ]
