# Generated by Django 6.0.2 on 2026-03-24 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du poste')),
                ('description', models.TextField(blank=True, help_text='Détails sur le poste (horaires, consignes…)', verbose_name='Description')),
                ('required_count', models.PositiveIntegerField(default=1, verbose_name='Nombre de personnes requises')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='events.eventpage', verbose_name='Événement')),
            ],
            options={
                'verbose_name': 'Poste',
                'verbose_name_plural': 'Postes',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la personne')),
                ('role', models.CharField(blank=True, help_text='Ex : bière uniquement, navette frigo…', max_length=150, verbose_name='Rôle spécifique')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='events.eventstation', verbose_name='Poste')),
            ],
            options={
                'verbose_name': 'Affectation',
                'verbose_name_plural': 'Affectations',
                'ordering': ['name'],
            },
        ),
    ]
