# Generated by Django 6.0.2 on 2026-02-20 10:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_eventpage_notes_eventimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='notes',
            field=wagtail.fields.StreamField([('richtext', 0), ('url', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Texte'}), 1: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL externe', 'label': 'Lien'})}, verbose_name='Notes et Comptes-rendus'),
        ),
    ]
