# Generated by Django 6.0.2 on 2026-03-31 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du matériel')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité en stock')),
            ],
            options={
                'verbose_name': 'Matériel',
                'verbose_name_plural': 'Matériels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=200, verbose_name="Nom de l'emprunteur")),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date du prêt')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customdocument', verbose_name='Convention de prêt')),
            ],
            options={
                'verbose_name': 'Prêt',
                'verbose_name_plural': 'Prêts',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LoanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité prêtée')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_items', to='equipment.equipment', verbose_name='Matériel')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='equipment.equipmentloan', verbose_name='Prêt')),
            ],
            options={
                'verbose_name': 'Ligne de prêt',
                'verbose_name_plural': 'Lignes de prêt',
                'ordering': ['equipment__name'],
            },
        ),
    ]
