# Generated by Django 6.0.2 on 2026-03-31 18:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentloan',
            options={'ordering': ['-start_date'], 'verbose_name': 'Prêt', 'verbose_name_plural': 'Prêts'},
        ),
        migrations.RemoveField(
            model_name='equipmentloan',
            name='date',
        ),
        migrations.AddField(
            model_name='equipmentloan',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de fin'),
        ),
        migrations.AddField(
            model_name='equipmentloan',
            name='is_finalized',
            field=models.BooleanField(default=False, verbose_name='Finalisé'),
        ),
        migrations.AddField(
            model_name='equipmentloan',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de début'),
        ),
    ]
