# Generated by Django 6.0.2 on 2026-05-17 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(blank=True, help_text="Question posée à l'IA (analyse globale).", verbose_name='Question')),
                ('content', models.TextField(verbose_name="Réponse de l'IA")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_summaries', to='wagtaildocs.document', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Résumé IA',
                'verbose_name_plural': 'Résumés IA',
                'ordering': ['-created_at'],
            },
        ),
    ]
