# Generated by Django 6.0.2 on 2026-05-17 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('ia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_summaries', to='core.customdocument', verbose_name='Document'),
        ),
    ]
